### ISSUE TITLE
clojurescript core things not resolved in other namespaces

### ISSUE THREAD

**Issue by dpsutton** [clojure-emacs/cljs-tooling#22]
If i'm in `cljs.user`, I can find information about vars in my namespace, but I can't find info about vars brought in from clojurescript core. 

Ie, 
```
(--> 
  op  "info"
  session  "846fed44-d63a-4dc1-b123-48f51d506853"
  ns  "cljc-bug.core"
  symbol  "def"
  id  "44"
)
(<-- 
  id  "44"
  session  "846fed44-d63a-4dc1-b123-48f51d506853"
  status  ("done" "no-info")
)
```

Ideally, I'd like for this to find the info. Raised in an issue on CIDER here [issue 1358](https://github.com/clojure-emacs/cider/issues/1358)

**Comment by dpsutton** [comment]
So, looking into this, I think `def` is a special case. Everything seems to work

ie, 
```
(--> 
  op  "info"
  session  "e204dac8-46dc-4703-b47a-a4c4f2d74fa8"
  ns  "cljs.user"
  symbol  "defn"
  id  "19"
)
(<-- 
  arglists-str  "([name doc-string? attr-map? [params*] prepost-map? body] [n..."
  column  1
  doc  "Same as (def name (core/fn [params* ] exprs*)) or (def
    n..."
  file  "jar:file:/home/dan/.m2/repository/org/clojure/clojurescript/..."
  id  "19"
  line  3008
  name  "defn"
  ns  "cljs.core"
  resource  "cljs/core.cljc"
  session  "e204dac8-46dc-4703-b47a-a4c4f2d74fa8"
  status  ("done")
)
```

And running 
```
cljs-tooling.info> (keys (a/public-macros 'cljs.core))
(unsafe-bit-and macroexpand unchecked-remainder-int when-first cond->> bit-set import-macros while satisfies? unchecked-subtract-int ns-unmap bit-shift-right aget specify vswap! caching-hash bit-shift-left coercive-not dec < this-as .. delay unchecked-negate simple-benchmark unchecked-inc-int js-str bit-shift-right-zero-fill implements? goog-define pos? specify! if-not alength bit-xor doseq unsigned-bit-shift-right neg? unchecked-float undefined? deftype mask when-let divide coercive-boolean <= if-some * min lazy-seq js-delete truth_ js-debugger let -> coercive-not= doto areduce double bit-and-not unchecked-add-int fn short unchecked-double string? js-arguments unchecked-multiply-int as-> when-not when int > keyword? unchecked-multiply gen-apply-to some->> unchecked-dec defn float js-in es6-iterable amap declare - hash-set or extend-type macroexpand-1 bit-test defmethod time zero? unchecked-dec-int memfn js-obj nil? extend-protocol cond-> dotimes bit-and reify instance? load-file* defonce unchecked-add identical? unchecked-divide-int defn- defprotocol unchecked-subtract assert true? array letfn / bitpos bit-or vector >= loop bit-flip js-mod with-out-str condp cond some-> ns-interns for binding array-map unchecked-byte defmacro unchecked-short inc with-redefs bit-clear list + aset defmulti str coercive-= hash-map if-let false? case exists? bit-not byte max == lazy-cat comment copy-arguments unsafe-cast defrecord make-array unchecked-negate-int unchecked-inc and number? js-comment symbol? when-some unchecked-char ->> js-inline-comment)
cljs-tooling.info> 
```
returns that there are a bunch of public macros. Its just that `def` doesn't seem to be in there.

**Comment by arichiardi** [comment]
I am saying this because in `replumb` for some info I access to the compiler state directly in order to read info: https://github.com/Lambda-X/replumb/blob/master/src/cljs/replumb/repl.cljs#L666

You can try a couple of functions from [the ast namespace](https://github.com/Lambda-X/replumb/blob/master/src/cljs/replumb/ast.cljs) and also if you like, read the [related blog post](http://lambdax.io/blog/posts/2016-03-22-replumb-ast.html).

**Comment by bbatsov** [comment]
Not sure whether @gtrak and @cichli work on the project anymore (haven't heard from them in a while). If someone wants to maintain it - just ping me and I'll make you a committer. It's a pretty important bit of the CIDER ecosystem, but it hasn't really progressed in the past one year.

**Comment by dpsutton** [comment]
@bbatsov I've got it cloned. If I need to do any PR's and they sit for a bit I'll take commit rights but I don't think that's needed yet. We'll see how it goes

**Comment by arichiardi** [comment]
After the rewrite in #24 I am going to check that this does not happen anymore

**Comment by arichiardi** [comment]
`def` is a special symbol and we might need to do some special about it

**Comment by arichiardi** [comment]
As future reference, `lumo`does this: https://github.com/anmonteiro/lumo/blob/master/src/cljs/snapshot/lumo/repl.cljs#L1409

**Comment by arichiardi** [comment]
Ok fixed
