### ISSUE TITLE
Var info fails for vars of the same namespace in 0.3.0

### ISSUE THREAD

**Issue by dpsutton** [clojure-emacs/cljs-tooling#28]
Running into issues with 0.3.0 with navigating to a var's definition. To recreate, attempt to navigate to a var defined in the same namespace. Getting "user-error: Symbol ‘thing’ not resolved" and no-info back in the nrepl logs.

I built cider-nrepl and pointed cljs-tooling back at 0.2.0 (currently went through 0.3.0-snapshot and 0.3.0) and the navigation is restored.

I was gonna jump into this myself but I see that there was a lot of work around self-hosted so I was wondering if @arichiardi might point me in the right direction first.

**Comment by arichiardi** [comment]
Ok, there might be a bug, what op is it sending? With that I can look into `cider-nrepl` and see what is called here.

Thanks for reporting!

**Comment by arichiardi** [comment]
Can you dump the of by any chance? Not that I don't trust you, but this lib receives symbols so I may just not sure if a var `#'` is right and would need to check in `cider-nrepl` as well.

Not at the keyboard now so no rush

**Comment by dpsutton** [comment]
dump the what? Do you want nrepl logs?

**Comment by dpsutton** [comment]
successful under 0.2.0:
``` clojure
(-->
  id         "19"
  op         "info"
  session    "6361d3ab-9109-4aa3-8e96-75aab0c2472d"
  time-stamp "2018-10-30 09:38:41.504013515"
  ns         "breeze.jib.components.patient.problem-list"
  symbol     "ProblemList"
)
(<--
  id         "19"
  session    "6361d3ab-9109-4aa3-8e96-75aab0c2472d"
  time-stamp "2018-10-30 09:38:41.509380438"
  column     1
  doc        ""
  file       "file:/home/dan/ops/projects/breeze_ehr/jib/src/breeze/jib/co..."
  line       451
  name       "ProblemList"
  ns         "breeze.jib.components.patient.problem-list"
  status     ("done")
)
```

unsuccessful under 0.3.0

``` clojure
(-->
  id         "13"
  op         "info"
  session    "f759e6aa-9573-4acb-be1e-ef0dc6e1918d"
  time-stamp "2018-10-30 09:40:54.997697889"
  ns         "breeze.jib.components.patient.problem-list"
  symbol     "ProblemList"
)
(<--
  id         "13"
  session    "f759e6aa-9573-4acb-be1e-ef0dc6e1918d"
  time-stamp "2018-10-30 09:40:55.087931411"
  status     ("done" "no-info")
)
```

**Comment by arichiardi** [comment]
Great that's awesome. Is `ProblemList` a record?

I am suspecting that broken as I do not recall tests for them.

**Comment by dpsutton** [comment]
No it is not a record, it's a `defcomponent` for react and I think it ends up as a function. In either case here's an example that is just a simple function that fails:

``` clojure
(-->
  id         "13"
  op         "info"
  session    "b2096315-919d-48fd-9904-9a64a321201a"
  time-stamp "2018-10-30 09:48:46.871739699"
  ns         "breeze.jib.components.patient.problem-list"
  symbol     "code-searcher"
)
(<--
  id         "13"
  session    "b2096315-919d-48fd-9904-9a64a321201a"
  time-stamp "2018-10-30 09:48:46.984293600"
  status     ("done" "no-info")
)
```

code-searcher is a simple `defn`.

**Comment by arichiardi** [comment]
🤔🤔 Ok thank you all tests are passing here so it might be two only two things:

* Something is not right in the ClojureScript state

* The `cljs-tooling.info/info` body, which contains when `cond-let` clauses, for some reason does not reach the "right" one and short circuits early.

In any case I will have a bit of time to debug this, I just wanted to give you a bit more info in case you want to have a look.

**Comment by dpsutton** [comment]
Thanks everyone! :+1:
