### ISSUE TITLE
cider-find-keyword fails with "Can't find namespace"

### ISSUE THREAD

**Issue by paroda** [clojure-emacs/cljs-tooling#31]
When a source file does't have a single **def** form, **cljs-tooling.util.analysis/find-ns** return value has **{}** for the key **:defs**. Since **cider.nrepl.middleware.ns/ns-path** checks this through **cljs-tooling.info/info** to find the source file path, cider utilities like **cider-find-keyword** fails with message "Can't find namespace".

Usually it should not be an issue. Just in the particular case of a re-frame project, it is common to have separate files for just the subscriptions and/or event registrations. They won't be having any **def** form otherwise. Looking up the event and subscription definitions is very helpful and easy with **cider-find-keyword**. However, due to lack of **def** forms, this doesn't work. Workaround is to just remember to add at least one **def** form (dummy).

It would be very convinient if the library can be enhanced to tackle this case and at least the **:file** be present instead of just the empty map **{}**.

**Comment by arichiardi** [comment]
Oh that is a peculiar way the compiler state is populated it seems. Kinda makes sense actually.

Probably we would still need to do what you said for coherence. I will think about it and of course feedback/PRs to review/small test (we have a required dummy file we require for tests - we could create a re-frame one) are always welcome!

**Comment by paroda** [comment]
Tried to see if I can do something about it, but hit a dead-end. Now I see that, it is dependent on the analysis done by **cljs.analyzer.api/analyze-file**. And that it self has the source file path only in the **:defs** map. Looks like no easy way to get the file path without doing a custom analysis of the files here as well. That would be overkill. Maybe some other approach needed.

**Comment by arichiardi** [comment]
Yes it seems like it would be a static analysis thing. Well, the compiler is actually doing static analysis in a way. 

Worth opening an issue in ClojureScript maybe just to test the waters?

**Comment by paroda** [comment]
Yeah, closing it.
